using System;
using PS.SuperNDT.UI.Models;

namespace PS.SuperNDT.UI.Services;

public sealed class ReportConfigurationService
{
    private ReportConfigurationModel _configuration;

    public ReportConfigurationService()
    {
        _configuration = new ReportConfigurationModel
        {
            StandardReference = "AERB / ISO 5579",
            ApprovalAuthority = "Authorized Level-III Inspector",
            FooterText = "Generated by PS SuperNDT Platform"
        };
    }

    public ReportConfigurationModel Get()
    {
        return _configuration;
    }

    public void Update(
        ReportConfigurationModel configuration)
    {
        if (configuration == null)
        {
            throw new ArgumentNullException(
                nameof(configuration));
        }

        configuration.UpdatedOn = DateTime.Now;

        _configuration = configuration;
    }
}